meta:
    job_name: "Circle_North_Pole_F16"
    description: "Subsonic F16 North Pole Circumnavigation"

vehicle:
    model: "F16_Circumnavigate"
    overrides:

instructions:
    earth_model: "WGS84"
    gravity_type: "J2"
    integrator: "RK4"
    simulate: true
    wind: false
    perform_trim: false
    compare: true
    t0_s: 0.0
    tf_s: 180.0
    dt_s: 0.012

output:
    save_data: true
    show_plots: false
    plots:
        6dof: true
        attitude: true
        controls: true
        aerodynamics: true
        geodetic: true
        ned_velocity: true

compare:
    path: "verification_data"
    save_compare: true
    plot_values: true
    show_values: true
    plot_error: true
    show_error: false
    plots:
        6dof: true
        attitude: true
        controls: true
        aerodynamics: true
        geodetic: true
        ned_velocity: true

initial_conditions:
    h_ft: 10000
    lat_deg: 89.95
    long_deg: -45

    u_n_fps: 0
    v_n_fps: 563.643
    w_n_fps: 0

    p_dps: 0
    q_dps: -0.004178073
    r_dps: 0
    phi_deg: 0
    theta_deg: 2.453813535191715
    psi_deg: 90

    dela_ach_deg: -0.00022
    dele_ach_deg: -0.73965
    delr_ach_deg: 0.0001635
    delt_ach_pct: 10.47

control:
    sas: true
    speedbrake: false
    autopilot:
        enabled: true
        enable_time_s: 0
        h_ft: 9994.5
        V_mps: 171.79
    circumnavigator: 1
    type: "no_lag"