meta:
    job_name: "Tumbling_Brick_No_Damping"
    description: "Tumbling Brick, no damping"

vehicle:
    model: "Dragless Brick"
    overrides:

instructions:
    earth_model: "WGS84"
    gravity_type: "J2"
    integrator: "RK45"
    simulate: true
    compare: true
    t0_s: 0.0
    tf_s: 30.0
    dt_s: 0.012

output:
    save_data: true
    show_plots: false
    plots:
        6dof: true
        attitude: true
        controls: false
        aerodynamics: true
        geodetic: true
        ned_velocity: true

compare:
    path: "verification_data"
    save_compare: true
    plot_values: true
    show_values: true
    plot_error: true
    show_error: false
    plots:
        6dof: true
        attitude: true
        controls: false
        aerodynamics: true
        geodetic: true
        ned_velocity: true

initial_conditions:
    h_ft: 30000
    lat_deg: 0
    long_deg: 0

    u_n_fps: 0
    v_n_fps: 0
    w_n_fps: 0

    p_dps: 10
    q_dps: 20
    r_dps: 30
    phi_deg: 0
    theta_deg: 0
    psi_deg: 0