meta:
    job_name: "F16_Steady_Flight_Test"
    description: "F16 Test"

vehicle:
    model: "F16"
    overrides:

instructions:
    earth_model: "WGS84"
    gravity_type: "J2"
    integrator: "RK4"
    wind: false
    simulation:
        enabled: true
        t0_s: 0.0
        tf_s: 10.0
        dt_s: 0.012
    perform_trim: true
    analysis:
        comparison:
            enabled: false

output:
    save_data: true
    show_plots: true
    plots:
        6dof: true
        attitude: true
        controls: true
        aerodynamics: true
        air_data: true
        geodetic: true
        ned_velocity: true
        forces: true
        load_factors: true
        3d_trajectory: true

initial_conditions:
    h_ft: 10013
    lat_deg: 36.019167
    long_deg: -75.674444

    u_n_mps: 152
    v_n_mps: 0
    w_n_mps: 0

    p_dps: 0
    q_dps: 0
    r_dps: 0
    phi_deg: 0
    theta_deg: 2.643330876
    psi_deg: 0

trim:
    trim_mode: "straight_and_level"

control:
    sas: true
    speedbrake: false
    ap: false
    circumnavigator: false