meta:
    job_name: "Dropped_Sphere_Wind_Shear"
    description: "Dropped Sphere, wind shear (WGS-84 earth)"

vehicle:
    model: "Cannonball"
    overrides:

instructions:
    earth_model: "WGS84"
    gravity_type: "J2"
    integrator: "RK45"
    simulate: true
    compare: true
    t0_s: 0.0
    tf_s: 30.0
    dt_s: 0.012

wind:
    wind_type: "polynomial"
    params:
        dir_deg: 90
        slope: 0.003
        offset: -6.096

output:
    save_data: true
    show_plots: false
    plots:
        6dof: true
        attitude: true
        controls: false
        aerodynamics: true
        geodetic: true
        ned_velocity: true

compare:
    path: "verification_data"
    save_compare: true
    show_plots: true
    plot_error: false
    plots:
        6dof: true
        attitude: true
        controls: false
        aerodynamics: true
        geodetic: true
        ned_velocity: true

initial_conditions:
    h_ft: 30000
    lat_deg: 0
    long_deg: 0

    u_n_fps: 0
    v_n_fps: 0
    w_n_fps: 0

    p_rps: 0
    q_rps: 0
    r_rps: 0
    phi_deg: 0
    theta_deg: 0
    psi_deg: 0