meta:
    job_name: "X15_Dutch_Roll"
    description: "X-15 Mach 3.0 Rudder Imuplse"

vehicle:
    model: "X15"

instructions:
    simulate: true
    perform_trim: false
    perform_linearization: false
    t0_s: 0.0
    tf_s: 25.0
    dt_s: 0.012

output:
    save_data: true
    save_dir: "./output_data/"
    figures:
        6dof: true
        attitude: true
        controls: true
        aerodynamics: true
        geodetic: true
        ned_velocity: true

initial_conditions:
    Mach: 3.0
    alpha_deg: 0.0
    beta_deg: 0.0
    h_m: 21336.0
    phi_deg: 0.0
    theta_deg: 0.0
    psi_deg: 0.0
    dela_ach_deg: 0.0
    dele_ach_deg: 0.0
    delr_ach_deg: 0.0
    lat_deg: 32.335556
    long_deg: -106.405833
    m_fuel_kg: 0.0

control:
    type: "doublet"
    amplitude: 4.0
    t1_s: 1.0
    t2_s: 1.5
    t3_s: 2.0
    aileron: false
    elevator: false
    rudder: true
    Kq: 12.0
    Kp: -6.0
    Kyar: 8.0
    Kr: 0.0 # 8.0
    throttle_percent: 0.0
    dela_cmd_deg: 0.0
    dele_cmd_deg: 0.0
    delr_cmd_deg: 0.0