meta:
    job_name: "X15_Descending_Turn"
    description: "X-15 Mach 2.4 Descending Turn with Trim"

vehicle:
    model: "X15"

instructions:
    eom: "WGS84"
    integrator: "RK45"
    simulate: true
    perform_trim: true
    perform_linearization: false
    compare: false
    t0_s: 0.0
    tf_s: 10.0
    dt_s: 0.005

output:
    save_data: true
    show_plots: false
    plots:
        6dof: true
        attitude: true
        controls: true
        aerodynamics: true
        geodetic: true
        ned_velocity: true

initial_conditions:
    Mach: 2.4
    alpha_deg: 1.0
    beta_deg: 0.0
    h_m: 16500.0
    phi_deg: 0.0
    theta_deg: 1.0
    psi_deg: 0.0
    dela_ach_deg: 0.0
    dele_ach_deg: 0.0
    delr_ach_deg: 0.0
    lat_deg: 37.3
    long_deg: -115.8
    m_fuel_kg: 0.0

trim:
    trim_mode: "descending_turn"
    # alpha_deg: 0
    # beta_deg: 0
    # h_m: 16500.0
    # p_dps: 0
    # q_dps: 0
    # r_dps: 0
    # phi_deg: 0
    theta_deg: 1
    # psi_deg: 0.0
    # phidot_dps: 0
    # thetadot_dps: 0
    psidot_dps: 2.0
    dela_ach_deg: -1.0
    dele_ach_deg: -1.0
    delr_ach_deg: 1.0

control:
    type: "doublet"
    amplitude: 1.5
    t1_s: 0.0
    t2_s: 1.0
    t3_s: 2.0
    aileron: false
    elevator: false
    rudder: false
    sas: true
    Kq: 12.0
    Kp: -6.0
    Kyar: 8.0
    Kr: 8.0
    throttle_percent: 0.0
    speedbrake: False