meta:
    job_name: "X15_Descending_Turn_No_Trim"
    description: "X-15 Mach 2.4 Descending Turn without Trim"

vehicle:
    model: "X15"
    overrides:

instructions:
    earth_model: "WGS84"
    gravity_type: "J2"
    integrator: "RK45"
    wind: false
    simulation:
        enabled: true
        t0_s: 0.0
        tf_s: 10.0
        dt_s: 0.005
    perform_trim: false
    analysis:
        linearization:
            enabled: true
            show_plots: true
            eigenvalues: true
            pole_zero_map: true
            bode:
                enabled: true
                inputs: ['dele', 'dela']     # Restrict to prevent massive grid plots
                outputs: ['q', 'p', 'phi', 'theta']
            step_response:
                enabled: true
                target_input: 'dele'
                t_end: 20.0

output:
    save_data: true
    show_plots: true
    plots:
        6dof: true
        attitude: true
        controls: true
        aerodynamics: true
        air_data: true
        geodetic: true
        ned_velocity: true
        forces: true
        load_factors: true
        3d_trajectory: true

initial_conditions:
    Mach: 2.4
    alpha_deg: 1.0
    beta_deg: 0.0
    h_m: 16500.0
    phi_deg: 0.0
    theta_deg: 1.0
    psi_deg: 0.0
    dela_ach_deg: 0.0
    dele_ach_deg: 0.0
    delr_ach_deg: 0.0
    lat_deg: 37.3
    long_deg: -115.8
    m_fuel_kg: 0.0

trim:
    trim_mode: "descending_turn"
    # alpha_deg: 0
    # beta_deg: 0
    # h_m: 16500.0
    # p_dps: 0
    # q_dps: 0
    # r_dps: 0
    # phi_deg: 0
    theta_deg: -9
    # psi_deg: 0.0
    # phidot_dps: 0
    # thetadot_dps: 0
    psidot_dps: 2.0
    dela_ach_deg: -1.0
    dele_ach_deg: -1.0
    delr_ach_deg: 1.0

control:
    type: "doublet"
    amplitude: 1.5
    t1_s: 0.0
    t2_s: 1.0
    t3_s: 2.0
    aileron:
        enabled: false
    elevator:
        enabled: false
    rudder:
        enabled: false
    sas: true
    Kq: 12.0
    Kp: -6.0
    Kyar: 8.0
    Kr: 8.0
    throttle_percent: 0.0
    speedbrake: False