meta:
    job_name: "Trim_Check_Subsonic_F16"
    description: "Subsonic F16 Trim Check"

vehicle:
    model: "F16"
    overrides:

instructions:
    earth_model: "WGS84"
    gravity_type: "J2"
    integrator: "RK45"
    simulation:
        enabled: true
        t0_s: 0.0
        tf_s: 180.0
        dt_s: 0.012
    analysis:
        comparison:
            enabled: true
            path: "verification_data"
            save_compare: true
            plot_values: true
            show_values: true
            plot_error: true
            show_error: false
            plots:
                6dof: true
                attitude: true
                controls: true
                aerodynamics: true
                air_data: true
                geodetic: true
                ned_velocity: true

output:
    save_data: true
    show_plots: false
    plots:
        6dof: true
        attitude: true
        controls: true
        aerodynamics: true
        air_data: true
        geodetic: true
        ned_velocity: true

initial_conditions:
    h_ft: 10013
    lat_deg: 36.019167
    long_deg: -75.674444

    u_n_fps: 400
    v_n_fps: 400
    w_n_fps: 0

    p_dps: 0.002954344
    q_dps: -0.002954344
    r_dps: 0
    phi_deg: 0
    theta_deg: 2.653813535191715
    psi_deg: 45

    dela_ach_deg: -0.00022
    dele_ach_deg: -0.73965
    delr_ach_deg: 0.0001635
    delt_ach_pct: 10.47

control:
    sas: true
    speedbrake: false
    ap: false
    circumnavigator: false